MVC_TuinCentrum/Controllers/PlantController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_TuinCentrum.Models;
using System.IO;
using MVC_TuinCentrum.Filters;

namespace MVC_TuinCentrum.Controllers
{
    [StatistiekActionFilter]
    public class PlantController : Controller
    {
        private MVCTuinCentrumEntities db = new MVCTuinCentrumEntities();

        // GET: Plant
        public ActionResult Index()
        {
            var planten = db.Planten.Include(p => p.Leverancier).Include(p => p.Soort);
            return View(planten.ToList());
        }

        // GET: Plant/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plant plant = db.Planten.Find(id);
            if (plant == null)
            {
                return HttpNotFound();
            }
            return View(plant);
        }

        // GET: Plant/Create
        public ActionResult Create()
        {
            ViewBag.Levnr = new SelectList(db.Leveranciers, "LevNr", "Naam");
            ViewBag.SoortNr = new SelectList(db.Soorten, "SoortNr", "Naam");
            return View();
        }

        // POST: Plant/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PlantNr,Naam,SoortNr,Levnr,Kleur,VerkoopPrijs")] Plant plant)
        {
            if (ModelState.IsValid)
            {
                db.Planten.Add(plant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Levnr = new SelectList(db.Leveranciers, "LevNr", "Naam", plant.Levnr);
            ViewBag.SoortNr = new SelectList(db.Soorten, "SoortNr", "Naam", plant.SoortNr);
            return View(plant);
        }

        // GET: Plant/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plant plant = db.Planten.Find(id);
            if (plant == null)
            {
                return HttpNotFound();
            }
            ViewBag.Levnr = new SelectList(db.Leveranciers, "LevNr", "Naam", plant.Levnr);
            ViewBag.SoortNr = new SelectList(db.Soorten, "SoortNr", "Naam", plant.SoortNr);
            return View(plant);
        }

        // POST: Plant/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PlantNr,Naam,SoortNr,Levnr,Kleur,VerkoopPrijs")] Plant plant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(plant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Levnr = new SelectList(db.Leveranciers, "LevNr", "Naam", plant.Levnr);
            ViewBag.SoortNr = new SelectList(db.Soorten, "SoortNr", "Naam", plant.SoortNr);
            return View(plant);
        }

        // GET: Plant/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plant plant = db.Planten.Find(id);
            if (plant == null)
            {
                return HttpNotFound();
            }
            return View(plant);
        }

        // POST: Plant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Plant plant = db.Planten.Find(id);
            db.Planten.Remove(plant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public ViewResult Uploaden(int id)
        {
            return View(id);
        }

        [HttpPost]
        public ActionResult FotoUpload(int id)
        {
            if (Request.Files.Count > 0)
            {
                var foto = Request.Files[0];
                var absoluutPadNaarDir = this.HttpContext.Server.MapPath("~/Images/Fotos");
                var absoluutPadNaarFoto = Path.Combine(absoluutPadNaarDir, id + ".jpg");
                foto.SaveAs(absoluutPadNaarFoto);
            }
            return RedirectToAction("Index");
        }

        public ActionResult FindPlantenBySoortNaam(string soortnaam)
        {
            List<Plant> plantenLijst = new List<Plant>();
            plantenLijst = (from plant in db.Planten.Include("Soort")
                            where plant.Soort.Naam.StartsWith(soortnaam)
                            select plant).ToList();
            return View(plantenLijst);
        }

        public ActionResult FindPlantenByLeverancier(int? levnr)
        {
            List<Plant> plantenLijst = new List<Plant>();
            plantenLijst = (from plant in db.Planten.Include("Leverancier")
                            where plant.Leverancier.LevNr == levnr
                            select plant).ToList();
            return View(plantenLijst);
        }

        public ActionResult FindPlantenBetweenPrijzen(decimal minPrijs, decimal maxPrijs)
        {
            List<Plant> plantenLijst = new List<Plant>();
            plantenLijst = (from plant in db.Planten
                            where plant.VerkoopPrijs >= minPrijs && 
                            plant.VerkoopPrijs <= maxPrijs
                            select plant).ToList();
            ViewBag.minPrijs = minPrijs;
            ViewBag.maxPrijs = maxPrijs;
            return View(plantenLijst);
        }

        public ActionResult FindPlantenVanEenKleur(string kleur)
        {
            List<Plant> plantenLijst = new List<Plant>();
            plantenLijst = (from plant in db.Planten
                            where plant.Kleur == kleur
                            select plant).ToList();
            ViewBag.Kleur = kleur;
            return View(plantenLijst);
        }

        [Route("plantinfo/{id:int}")]
        public ActionResult FindPlantById(int id)
        {
            var plant = db.Planten.Find(id);
            if (plant != null)
            {
                return View("Details", plant);
            }
            else
            {
                var planten = db.Planten.Include(p => p.Soort);
                return View("Index", planten.ToList());
            }
        }

        [Route("plantinfo/{naam}")]
        public ActionResult FindPlantByName(string naam)
        {
            var plant = (from p in db.Planten
                         where p.Naam == naam
                         select p).FirstOrDefault();
            if (plant != null)
            {
                return View("Details", plant);
            }
            else
            {
                var planten = db.Planten.Include(p => p.Leverancier).Include(p => p.Soort);
                return View("Index", planten.ToList());
            }
        }

        [Route("plantenprijzen/{btw:values(inclusief|exclusief)}", Name="btwinex")]
        public ActionResult PrijsLijst(string btw)
        {
            ViewBag.btw = btw;
            return View(db.Planten.ToList());
        }
    }
}

MVC_TuinCentrum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Tuincentrum", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink(Resources.Teksten.Planten, "Index", "Plant")</li>
                    <li>@Html.ActionLink(Resources.Teksten.Soorten, "Index", "Soort")</li>
                    <li>@Html.ActionLink(Resources.Teksten.Leveranciers, "Index", "Leverancier")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href='@Url.Action(ViewBag.Title, new { culture = "nl-BE" })'>
                            <img src="~/Images/nederlands.png" alt="nederlands" />
                        </a>
                    </li>
                    <li>
                        <a href='@Url.Action(ViewBag.Title, new { culture = "fr-BE" })'>
                            <img src="~/Images/francais.png" alt="français" />
                        </a>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <img class="extramargin" src="~/Images/tuincentrum.png" alt="tuincentrumlogo" />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>